In [1]:
import tensorflow as tf
from tensorflow import random
import numpy as np
import tensorflow_probability as tfp

2022-06-26 07:41:02.013603: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


# Creating Tensors with tf.constant() #

In [ ]:
# Creating tensors with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [18]:
# check the no of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [19]:
# Create a vector
vector = tf.constant([10,10,6,7])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10,  6,  7], dtype=int32)>

In [20]:
# Check the dimension of a vector
vector.ndim

1

In [21]:
# Create a matrix
matrix = tf.constant([[10, 7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [22]:
matrix.ndim

2

In [23]:
# Create another matrix
matrix2 = tf.constant([[10, 7], [7,10],[5,6]],dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 5.,  6.]], dtype=float16)>

In [24]:
matrix2.ndim

2

In [25]:
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                      [12,13,14]],
                      [[13,15,16],
                       [16,17,18]]]
                      )
tensor
                   

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [12, 13, 14]],

       [[13, 15, 16],
        [16, 17, 18]]], dtype=int32)>

In [26]:
tensor.ndim

3

# Creating tensors with tf variable #

In [27]:
ctensor = tf.Variable([10, 7])
utensor = tf.constant([[10, 7]])
ctensor,utensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10,  7]], dtype=int32)>)

In [28]:
# Change elements in one of the elements in our changeble tensor
ctensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Change elements in one of the elements in our un-changeble tensor
utensor[0].assign(7)

# Creating Random tensors<br>
Random tensors are tensors of some arbitary size which contain random numbers

In [30]:
#Create two random (but the same) tensors
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [31]:
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [32]:
# Are they equal?
random1==random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

# Shuffle the order of tensors (Valueble for when you want to shuffle your data so the inherent order dosent effect learning) #

In [33]:
# not shuffled
nshuffled = tf.constant([[10,7],
                        [3,4],
                        [2,5]])
tf.random.shuffle(nshuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [34]:
tf.random.set_seed(42) # Global random seed
tf.random.shuffle(nshuffled,seed=42) # Operational seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [35]:
nshuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [36]:
# create a tensor with all ones
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [37]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# TURN NUMPY ARRAYS INTO TENSORS <br>
The main difference between them is that tensors can be run on a GPU (much faster for numerical computing)

In [38]:
# Create numpy array between 1 and 25
numpyA = np.arange(1,25, dtype=np.int32)
numpyA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [39]:
A = tf.constant(numpyA,shape=(2,3,4))
A.ndim
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# Getting information from tensors #

In [40]:
# Create a rank 4 tensor
rank4t = tf.zeros(shape=[2,3,4,5])
rank4t

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [41]:
rank4t[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [42]:
rank4t.shape , rank4t.ndim, tf.size(rank4t)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

# Get various attributes of the tensor #

In [43]:
print("Data type of every element: ",rank4t.dtype)
print("Number of dimensions: ", rank4t.ndim)
print("shape of tensor: ",rank4t.shape)
print("Elements along zeroth axis: ",rank4t.shape[0])
print("Elements along last axis: ",rank4t.shape[-1])
print("Total number of elements: ",tf.size(rank4t).numpy())

Data type of every element:  <dtype: 'float32'>
Number of dimensions:  4
shape of tensor:  (2, 3, 4, 5)
Elements along zeroth axis:  2
Elements along last axis:  5
Total number of elements:  120


# Indexing tensors
Tensors can be indexed like python lists

In [44]:
# Get the first 2 elements of each dimension
rank4t[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [49]:
# Get the first element from each dimension from each index except the final one
rank4t[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [50]:
# Create a rank 2 tensor (2 dimensions)
rank2t = tf.constant([[1,2],[3,4]])

In [71]:
# Get the last item of each row of the tensor
rank2t[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [57]:
rank2t

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [72]:
# Add extra dimension to our rank2 tensor 
rank3t = rank2t[...,tf.newaxis]
rank3t

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

# Alternative to tf.newaxis

In [74]:
tf.expand_dims(rank2t,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [75]:
tf.expand_dims(rank2t,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

# Manipulating tensors (tensor operations)

**Basic operations**

In [76]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [77]:
# Multiplication
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [78]:
# Substraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [79]:
# We can use the tensorflow built in function
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# Matrix multiplication #

**In machine learning, matrix multiplication is one of the most common tensor operations**

There are 2 rules that tensors(or matrices) need to fulfill if we are going to matrix multiply them:

1. The inner dimensions must match
2. The reuslting matrix has the shape of the outer dimensions

free demo website - www.matrixmultiplication.xyz

How to multiply matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [80]:
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [81]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [82]:
# Matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [84]:
# Create a tensor of (3,2) tensor
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
# Create another (3,2) tensor
Y = tf.constant([[7,8],
                [9,10],
                [11,12]])

In [ ]:
# Matrix multiply of tensors of same shape
# X @ Y - will recieve error message
# tf.matmul(X,Y) - will produce error

In [87]:
# Lets change the shape of y
reshapedY = tf.reshape(Y, shape=(2,3))

In [88]:
# Multiply x by reshape Y
X @ reshapedY

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [90]:
# Different method
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [91]:
# Changing the shape of X instead of Y
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [92]:
# Can do the same with transpose
X, tf.transpose(X),tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [93]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

# The dot product #

Matrix multiplication is also referred to as the dot product<br>
You can perform matrix multiplicaton using:<br>
* `tf.matmul()`<br>
* `tf.tesnordot()`

In [95]:
# Perform dot product on X and Y (Requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [96]:
# Perform dot product on X and Y (Y transposed)
tf.tensordot(tf.transpose(Y), X, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89, 116],
       [ 98, 128]], dtype=int32)>

In [98]:
# Perform matrix multiplication between X and Y (Reshaped)
tf.matmul(tf.reshape(X, shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [101]:
# Perform matrix multiplication between X and Y (Transposed)
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

# Changing the data type of a tensor #

In [3]:
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [4]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [5]:
# Change from float32 to float16 (Reduced precision)
D= tf.cast(B, dtype=tf.float16)
D.dtype

tf.float16

In [8]:
#change from int32 to float32
E =tf.cast(C,dtype = tf.float32)
E.dtype

tf.float32

# Aggregating tensors #

**Aggregating tensors = condensing them from multiple values down to a smaller amount of values**

In [9]:
# Get the absolute values
D = tf.constant([-7,-10])

In [10]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregation
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [32]:
import numpy as np
# Create a random tensor with values between 0 and 100
E = tf.constant(np.random.randint(0,100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 3, 51, 85, 65, 97, 11, 92, 66, 72, 56, 45, 26, 30, 19, 94, 19, 76,
       66, 71,  2, 67, 45, 51,  7, 75, 51, 88, 50, 20, 59, 61, 61,  1, 23,
       68, 63, 76,  3, 10, 31, 73, 31, 43, 67, 76, 45, 40, 94, 97, 97])>

In [16]:
tf.size(E), E.shape, E.ndim

50

In [20]:
# Find the minimum
tf.reduce_min(E).numpy()

5

In [21]:
# Find the maximum
tf.reduce_max(E).numpy()

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [23]:
#Find the mean
tf.reduce_mean(E).numpy()

49

In [24]:
#Find the sum
tf.reduce_sum(E).numpy()

2483

In [35]:
# Find the variance
tfp.stats.variance(E).numpy()

809

In [38]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32)).numpy()

28.457611

# Find the positional Minimum and Maximum #

In [20]:
# Create a new tensor finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [21]:
# Find the positinal maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [22]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [23]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [24]:
# CHeck equality
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [25]:
# FInd the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [27]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [28]:
# Find the minimum value of F
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# Squeezing a tensor (Removing all single dimensions) #

In [42]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [38]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
Gsq = tf.squeeze(G) # tf.squeez() removes all dimensions of size one
Gsq

# One hot encoding tensors #

In [48]:
# Create a list of indices
ilist = [0,1,2,3]

# One hot encode our list of indices
tf.one_hot(ilist,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [50]:
# Specify custom values for one hot encoding
tf.one_hot(ilist, depth=4,on_value="yo i love deep learning",off_value="I also likes to dancing")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learning', b'I also likes to dancing',
        b'I also likes to dancing', b'I also likes to dancing'],
       [b'I also likes to dancing', b'yo i love deep learning',
        b'I also likes to dancing', b'I also likes to dancing'],
       [b'I also likes to dancing', b'I also likes to dancing',
        b'yo i love deep learning', b'I also likes to dancing'],
       [b'I also likes to dancing', b'I also likes to dancing',
        b'I also likes to dancing', b'yo i love deep learning']],
      dtype=object)>

# Squarring, log, square root #

In [12]:
# Create a new tensor
H = tf.range(1,10)
H = tf.cast(H,tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [13]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.], dtype=float32)>

In [14]:
# Square root
tf.sqrt(H).numpy()

array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)

In [15]:
# Find the log
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and Numpy #

In [17]:
# Create a tensor directly from numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [19]:
# Convert tensor back to numpy array
np.array(J) , type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [20]:
# Convert tensor J to numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [27]:
J.numpy()[0]

3.0

In [32]:
# The default types of each are sligtly different
numpyJ = tf.constant(np.array([3.,7.,10.]))
tensorJ = tf.constant([3.,7.,10.])
# Check whether they are equal convert float64 numpy to float32
tf.cast(numpyJ,tf.float32)==tensorJ 

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([ True,  True,  True])>